# Generated by Django 3.0.5 on 2020-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafePassword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='key',
            field=models.CharField(default='weivni#$&RsdhbvuHGW$49784RBb', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
